[profile.default]
src = "contracts"
#src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"},{ access = "read-write", path = "/tmp/"}]
ffi = true

# Solidity compiler configuration
solc_version = "0.8.28"
evm_version = "paris"


[profile.remappings]
# ds-test = "lib/forge-std/lib/ds-test/src/"
forge-std = "lib/foundry-noir-helper/lib/forge-std/src/"
# foundry-noir-helper = "lib/foundry-noir-helper/src/"

[rpc_endpoints]
swellchain-testnet = { url = "${SWELL_CHAIN_TESTNET_RPC}", chain = "swellchain-testnet" }
#sepolia = "${SEPOLIA_RPC}"

[etherscan]
swellchain-testnet = { key = "${SWELL_CHAIN_TESTNET_PRIVATE_KEY}", url = "${SWELL_CHAIN_TESTNET_RPC}" }
#sepolia = { key = "${SEPOLIA_PRIVATE_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
