pragma solidity ^0.8.17;

import { UltraVerifier } from "./ultra-verifier/plonk_vk.sol";
//import "../circuits/target/contract.sol";

contract InsuranceClaimProofVerifier {

    string public version;

    UltraVerifier public verifier;

    constructor(UltraVerifier _verifier) {
        verifier = _verifier;
        version = "0.37.74";
    }

    /**
     * @notice - Verify the insurance claim proof
     * @param proof - The proof generated by the ZK circuit
     * @param publicInputs - The public inputs of the proof
     */
    function verifyInsuranceClaimProof(bytes calldata proof, bytes32[] calldata publicInputs) public view returns (bool) {
        bool proofResult = verifier.verify(proof, publicInputs);
        require(proofResult, "A given InsuranceClaimProof is not valid");
        return proofResult;
    }
}
