// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

import { InsuranceClaimProofVerifier } from "./circuit/InsuranceClaimProofVerifier.sol"; // generated by Noir/Groth16

/**
 * @notice - This is the Hospital Registry
 */
contract HospitalRegistry {

    mapping(address => bool) private hospitalPubkeys;

    constructor() {}

    /**
     * @dev - A hospital would register on-Chain.
     * @dev - Only hispital can call this function.
     */
    function registerHospital(address hospitalPubKey) public returns (address _hospitalPubKey) {
        require(hospitalPubkeys[hospitalPubKey] = false, "This hospital pubKey has already been registered");
        hospitalPubkeys[hospitalPubKey] = true;
    }
}