// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

import { InsuranceClaimProofVerifier } from "./circuit/InsuranceClaimProofVerifier.sol"; // generated by Noir/Groth16

/**
 * @notice - This is the Hospital Registry
 */
contract HospitalRegistry {

    constructor() {}

    /**
     * @dev - A hospital would register on-Chain.
     */
    function registerHospital(address hospitalPubKey) public returns (address _hospitalPubKey) {
        // [TODO]:
    }
}